### PR TITLE
COS-12 - Add SASS support

### PR DESCRIPTION
**Pull request by hbentota**
Added SASS support and proper directories.

### CODE REVIEW

**Comment by asharms26** [comment]
I'm not going to request a change here, but can you provide an example of something in Sass to ensure it works? Maybe a simple list of buttons with nested stylings?

#list-button{
    .list-button-item:{
        background:red;
    }
}

<ul id="list-button">
    <button class="list-button-item"></button>
</ul>

**Comment by RussianPrussian** [comment]
I'm okay with you committing this so long as you've verified that the sass is compiling. I'd rather not commit something we wont' be using.

**Comment by hbentota** [comment]
@asharms26 @RussianPrussian 

Yes I have tested this. We only require those minor configuration changes to add scss support.

When you do 'ng generate component test', it now creates scss files.

As for previously created css files, you can just replace the css file extension with .scss along with the .css references in the component.ts files.

**Comment by RussianPrussian** [comment]
Okay. Can you change those extensions for all existing css files before merging?

**Pull request merged**
